### ISSUE TITLE
CarPlay App not working with free developer account

### ISSUE THREAD

**Issue by timemaster5** [SpotCompiled/SpotveeC#12]
I found on another forum that downloading unmodified Spotify ipa and merging it with Spotilife deb (back then) was enough to keep the car play entitlements intact. Could a change of the app name cause the loss of the car play entitlements?

I wanted to modify the iPad myself, but I was not successful. The app crashes right after the splash.
Do I have right debs?

I use these for the current version:
com.eevee.spotify_4.0_iphoneos-arm64.deb
dev.theos.orion14_1.0.1_iphoneos-arm.deb
org.swift.protobuf.swiftprotobuf_1.26.0_iphoneos-arm64.deb

I also tried 32bit arm debs for eeve and swiftprotobuf

**Comment by yodaluca23** [comment]
I believe for CarPlay entitlements you need TrollStore. Though I believe CarPlay has a NowPlaying type thing, that should let you control it at least from the native NowPlaying API.

You have the swiftprotobuf arm version while all the others are arm64, you need to use all ether arm or arm64 standard.

**Comment by timemaster5** [comment]
Yes, NowPlaying API works. 

TrollStore. I've seen somewhere that what Trollstore did in the past is not possible in recent iOS versions. 

Maybe I am wrong, but I think the correct way is not to strip the entitlements (which probably means to use Pyzule, as one step it is reporting is "Restoring entitlements" or add them manually later. Pyzule has an option for it -x. 

I also found this article, which explains how to create the entitlements file https://georgegarside.com/blog/ios/custom-entitlement-ios-app-ipa/#create-an-entitlementsplist


> You have the swiftprotobuf arm version while all the others are arm64, you need to use all ether arm or arm64 standard.

Regarding this, sorry it was my fault in the previous message. I used both arm64 and also tried with both arm. But neither of these combinations worked ;( What I didn't find is arm64 release of orion14, maybe that is the problem as the ipa is probably arm64.

Anyway, correcting it in my previous message

**Comment by jvdweijden1981** [comment]
Still no working CarPlay with the latest version unfortunately. I use Sideloadly to install on my iPhone, IOS 17.5.1

**Comment by BLADLIFES** [comment]
help please. I'm from European Union. My Altstore PAL app say this when I try to add the source: "One or more apps in source "SpotCompiled" are missing a marketplacelD. This most likely means they are not notarized, which is not supported by this version of AltStore."

**Comment by yodaluca23** [comment]
Can y'all try the latest release, not the one with "ALTSTORESOURCE_ONLY".

**Comment by jvdweijden1981** [comment]
Still not working with CarPlay unfortunately. Installed v3.1.8_v8.9.76 with Sideloadly on iPhone 13 mini, IOS 17.5.1

**Comment by jvdweijden1981** [comment]
![Schermafbeelding 2024-09-25 122247](https://github.com/user-attachments/assets/1543f6e0-bce6-42aa-ba69-d6beb613036a)
This settings used.

**Comment by yodaluca23** [comment]
> ![Schermafbeelding 2024-09-25 122247](https://github.com/user-attachments/assets/1543f6e0-bce6-42aa-ba69-d6beb613036a)
> 
> This settings used.

Is that a free developer account? If so, then that's your problem. CarPlay only works with troll store or a paid developer account.

**Comment by jvdweijden1981** [comment]
Ok. Thanks for your help. That should be the issue, it is a free developer account. I didn't knew that CarPlay entitlements only work with paid developer accounts.

**Comment by timemaster5** [comment]
Oh, ok, I didn't know that either. Do we have someone willing to give us a signed version with the paid developer account  ?:) 

by the way, that means this issue is probably resolved.. Thank you
