### ISSUE TITLE
Cannot open app after last update (3.0.4)

### ISSUE THREAD

**Issue by p-sage** [SpotCompiled/SpotveeC#13]
Hi,
I cannot aopen the app after last update (3.0.4). When I click to open it, it crashes instantly and takes me back to the home screen. I tried to unisntall it and reinstall it via Sidestore but nothing very conclusive... Did I miss something?

**Comment by yodaluca23** [comment]
What iOS version

**Comment by p-sage** [comment]
It's iOS 17.5.1

**Comment by yodaluca23** [comment]
Fixed
