### ISSUE TITLE
EeveeSpotify not working through Google Cast

### ISSUE THREAD

**Issue by thegamerof17** [SpotCompiled/SpotveeC#15]
The Premium functionality works fine when listening directly through my phone or via Bluetooth, but as soon as I connect to a Google Cast device, the premium functionality disappears, only offering the Free features. As soon as I disconnect from the Cast device, the Premium functionality returns.

This was not an issue with the much older Spotilife version of the app, which I have continued using for now.

**Comment by yodaluca23** [comment]
This is because when using Google cast, or anything similar it tells that device to play it through the Spotify API, and turns your phone or whatever into a simple remote. Meaning it is not possible to spoof the premium status, please use bluetooth, this is not possible to fix.

**Comment by ivsege** [comment]
Older versions of Spotilife could do this. I wonder why it's not possible anymore.

**Comment by thegamerof17** [comment]
> Older versions of Spotilife could do this. I wonder why it's not possible anymore.

I'm not quite sure either. I listen via Cast half the time, so have been forced to stay on the older version of the app, which is annoying given how much nicer the current version is.

**Comment by yodaluca23** [comment]
> I'm not quite sure either. I listen via Cast half the time, so have been forced to stay on the older version of the app, which is annoying given how much nicer the current version is.

Just use Bluetooth...

**Comment by ivsege** [comment]
> > Older versions of Spotilife could do this. I wonder why it's not possible anymore.
> 
> I'm not quite sure either. I listen via Cast half the time, so have been forced to stay on the older version of the app, which is annoying given how much nicer the current version is.

Me too. I rolled back to the latest version of Spotilife.

**Comment by thegamerof17** [comment]
> > I'm not quite sure either. I listen via Cast half the time, so have been forced to stay on the older version of the app, which is annoying given how much nicer the current version is.
> 
> Just use Bluetooth...
It's not practical for me, as I'd have to keep the app open constantly, and can't watch a video whilst listening to music without the music stopping

**Comment by thegamerof17** [comment]
> > I'm not quite sure either. I listen via Cast half the time, so have been forced to stay on the older version of the app, which is annoying given how much nicer the current version is.
> 
> Just use Bluetooth...

It's not practical for me, as I'd have to keep the app open constantly, and can't watch a video whilst listening to music without the music stopping

**Comment by yodaluca23** [comment]
> I just tried the latest version but cannot cast because it can't find any devices on my network. 

Does it have network permissions enabled? Are you using a VPN or something that blocks local LAN access?

**Comment by ivsege** [comment]
> > I just tried the latest version but cannot cast because it can't find any devices on my network.
> 
> Does it have network permissions enabled? Are you using a VPN or something that blocks local LAN access?

Yes, I've enabled network permissions & not using a VPN. Spotilife can find my Google devices. Really strange.

**Comment by yodaluca23** [comment]
> Yes, I've enabled network permissions & not using a VPN. Spotilife can find my Google devices. Really strange.

What sideload method?

**Comment by ivsege** [comment]
> > Yes, I've enabled network permissions & not using a VPN. Spotilife can find my Google devices. Really strange.
> 
> What sideload method?

Sideloadly v0.50.3

**Comment by thegamerof17** [comment]
> Ok guys, I just tested it with the latest release, because I was curious as to what you all were saying about Spotilife, if Spotilife can do it, this should be able to, and I found surprisingly it worked! I was able to select songs in a playlist, skip more than 6, and didn't get any ads while using Google Cast, in my testing. Please try the latest version.

I've just tried the latest version, but it also can't find any devices on my network, despite the previous Eevee version doing so fine. Local network is enabled, and Spotilife picks them up. I did notice that the UI in the modern casting screen has changed slightly since last version, so I'm wondering if that's anything related.

If I connect to the device through the Spotilife version, the Premium controls show up fine in Eevee, although if I ask the Cast device to play Spotify (Google Home), the Eevee app only shows the free functions again. This does make sense, however Spotilife would bypass this after just pressing one button.

**Comment by ivsege** [comment]
> > Ok guys, I just tested it with the latest release, because I was curious as to what you all were saying about Spotilife, if Spotilife can do it, this should be able to, and I found surprisingly it worked! I was able to select songs in a playlist, skip more than 6, and didn't get any ads while using Google Cast, in my testing. Please try the latest version.
> 
> I've just tried the latest version, but it also can't find any devices on my network, despite the previous Eevee version doing so fine. Local network is enabled, and Spotilife picks them up. I did notice that the UI in the modern casting screen has changed slightly since last version, so I'm wondering if that's anything related.
> 
> If I connect to the device through the Spotilife version, the Premium controls show up fine in Eevee, although if I ask the Cast device to play Spotify (Google Home), the Eevee app only shows the free functions again. This does make sense, however Spotilife would bypass this after just pressing one button.

Which version of Eevee can find devices on your network? Might be worth rolling back to that version.

**Comment by yodaluca23** [comment]
> Which version of Eevee can find devices on your network? Might be worth rolling back to that version.

I don't know why that's happening for ya'll, it's working for me...

**Comment by ivsege** [comment]
> > Which version of Eevee can find devices on your network? Might be worth rolling back to that version.
> 
> I don't know why that's happening for ya'll, it's working for me...

What did you use to sideload?

**Comment by ivsege** [comment]
I've enabled local network sharing in settings, but I can't see any devices when trying to cast: 
![IMG_6684](https://github.com/user-attachments/assets/cbb22ef7-5f9f-438e-aac2-82bded721f39)

**Comment by yodaluca23** [comment]
> I've enabled local network sharing in settings, but I can't see any devices when trying to cast: 
> 
> ![IMG_6684](https://github.com/user-attachments/assets/cbb22ef7-5f9f-438e-aac2-82bded721f39)

I use SideStore, also tested on TrollStore.

**Comment by ivsege** [comment]
I just tried SideStore, and it can't find any devices either..

**Comment by thegamerof17** [comment]
> > > Ok guys, I just tested it with the latest release, because I was curious as to what you all were saying about Spotilife, if Spotilife can do it, this should be able to, and I found surprisingly it worked! I was able to select songs in a playlist, skip more than 6, and didn't get any ads while using Google Cast, in my testing. Please try the latest version.
> > 
> > 
> > I've just tried the latest version, but it also can't find any devices on my network, despite the previous Eevee version doing so fine. Local network is enabled, and Spotilife picks them up. I did notice that the UI in the modern casting screen has changed slightly since last version, so I'm wondering if that's anything related.
> > If I connect to the device through the Spotilife version, the Premium controls show up fine in Eevee, although if I ask the Cast device to play Spotify (Google Home), the Eevee app only shows the free functions again. This does make sense, however Spotilife would bypass this after just pressing one button.
> 
> Which version of Eevee can find devices on your network? Might be worth rolling back to that version.

Not quite sure, but the last version I tried (just before posting this issue) showed devices, but only the free controls when connected. This might sound silly, but how would I download a specific version on SideStore?

**Comment by thegamerof17** [comment]
> > I've enabled local network sharing in settings, but I can't see any devices when trying to cast:
> > ![IMG_6684](https://private-user-images.githubusercontent.com/2909566/358425846-cbb22ef7-5f9f-438e-aac2-82bded721f39.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5Mzc1NzksIm5iZiI6MTcyMzkzNzI3OSwicGF0aCI6Ii8yOTA5NTY2LzM1ODQyNTg0Ni1jYmIyMmVmNy01ZjlmLTQzOGUtYWFjMi04MmJkZWQ3MjFmMzkuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMjMyNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc0M2VkMDhiNWJiY2E3MmNlZmY5YjQ1NDU3NjNhOWZhNGViM2Q5MGI0YmI4N2JlY2UwOTMzNzU2NGMxN2I3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RxzrIAv5sNPxKG_xTOWv_PiJgfR1gQMzAfQ34mlztJA)
> 
> I use SideStore, also tested on TrollStore.

I'm using SideStore too, same issue with no devices showing up

**Comment by ivsege** [comment]
> I'm using SideStore too, same issue with no devices showing up

I gave up and downgraded to the latest Spotilife.

**Comment by thegamerof17** [comment]
> ything related.
> 
> If I connect to the device through the Spotilife version,

I've just never properly moved from Spotilife in the first place, it might look uglier but it at least plays music. Hopefully the modern one can be sorted at some point

**Comment by yodaluca23** [comment]
I just reinstalled, and now it is not showing WiFi devices for me as well... very strange...

**Comment by ivsege** [comment]
> I just reinstalled, and now it is not showing WiFi devices for me as well... very strange...

Reinstalled Spotvee?

**Comment by ivsege** [comment]
SpotveeC.v3.1.4_v8.9.66 isn't working either..

**Comment by yodaluca23** [comment]
Yea, ok, so this is what I did to fix it.
Delete whatever you have installed now.
Install the version with EeveeSpotify 4.0, (probably works with others, this is the one I tested)
Use Google cast give permission and whatever.
Upgrade to latest, (don't delete old just install over) and it should work.

**Comment by ivsege** [comment]
Great, that worked! 

Thanks for looking into this, and finding a fix.

**Comment by thegamerof17** [comment]
Thanks, I did try installing that version but due to my little knowledge I have seemingly eff'd up SideStore in the process, as I now have 11 App IDs...

**Comment by ivsege** [comment]
> Thanks, I did try installing that version but due to my little knowledge I have seemingly eff'd up SideStore in the process, as I now have 11 App IDs...

I used [Sideloadly](https://sideloadly.io/) on my PC with no issues.

**Comment by ivsege** [comment]
Update: After a few days of working, it randomly stopped. 

I deleted the latest version and installed version 4.0 again, and it works correctly.

**Comment by Agge0706** [comment]
I have the same problem as all of you do, does downloading EeveeSpotify 4.0 and then upgrading to the latest still work?

**Comment by yodaluca23** [comment]
> I have the same problem as all of you do, does downloading EeveeSpotify 4.0 and then upgrading to the latest still work?

Yes, downgrading then updating to the latest is working for me still as a workaround.

**Comment by Agge0706** [comment]
> > I have the same problem as all of you do, does downloading EeveeSpotify 4.0 and then upgrading to the latest still work?
> 
> Yes, downgrading then updating to the latest is working for me still as a workaround, to get Google cast to show devices.

Where do I find the older versions?

**Comment by yodaluca23** [comment]
> > > I have the same problem as all of you do, does downloading EeveeSpotify 4.0 and then upgrading to the latest still work?
> > 
> > 
> > Yes, downgrading then updating to the latest is working for me still as a workaround, to get Google cast to show devices.
> 
> Where do I find the older versions?

Depending on which version you're using, if you're using the one labeled ```ALTSTORESOURCE_ONLY``` then you can get the one from here https://github.com/SpotCompiled/SpotveeC/releases/download/v3.0.0/SpotveeC.v3.0.0_v8.9.42.ipa If your using the normal one without ```ALTSTORESOURCE_ONLY```, then you can get it from the Official EeveeSpotify repo https://github.com/whoeevee/EeveeSpotify/releases/download/swift4.0/EeveeSpotify-4.0-8.9.42.ipa
Simply downgrade, then verify Google Cast is working, then you can upgrade to the latest version https://github.com/SpotCompiled/SpotveeC/releases/latest

**Comment by yodaluca23** [comment]
> Sorry for my little knowledge but how do I know which version I use if its labeled ”ALTSTORESOURCE_ONLY” or not. 

Where did you get it from? Either way, if you use the wrong one, it'll just install a duplicate, instead of installing over, and you can just delete it and choose the other one.
