### ISSUE TITLE
Carplay not working properly

### ISSUE THREAD

**Issue by ThomasAdnum** [SpotCompiled/SpotveeC#16]
Hello! 

I just installed the app with ALtstore and it is working great, however when I use it with carplay, I cant access the album or any of my spotify playlist etc on the car HUD. It shows up as now play and I can skip songs, but that is all. 

Is there a fix to this?

**Comment by yodaluca23** [comment]
The NowPlaying API is all you'll be able to get without TrollStore, CarPlay requires TrollStore...
