### ISSUE TITLE
Question: Why Is There No “Very High” Audio Quality Support?

### ISSUE THREAD

**Issue by luhgarlicbread** [SpotCompiled/SpotveeC#2]
As the title says, I’m wondering why this tweak does not have “very high” audio quality support? I want my music as high quality as it can beeee!!

Ooo 999kbs song? Let’s gettt ittttt. You feel me?
Thanks!!

**Comment by yodaluca23** [comment]
This is server sided, so it's impossible...

**Comment by luhgarlicbread** [comment]
> This is server sided, so it's impossible...

Yeaaaa, what does that mean exactly? I know what it means for something to be server-sided, but what does that specifically imply in this scenario?

**Comment by zezking-toku** [comment]
> > This is server sided, so it's impossible...
> 
> Yeaaaa, what does that mean exactly? I know what it means for something to be server-sided, but what does that specifically imply in this scenario?

It means the we can not manipulate the data stored in the server unless we have server access. The other feature like Ads, limited skips are all done in the client side so we can tweak them.
