### ISSUE TITLE
Can't install anymore on AltStore Beta

### ISSUE THREAD

**Issue by bpresles** [SpotCompiled/SpotveeC#20]
With current/latest AltStore Beta it's not possible anymore to bypass the missing permissions warning and accept them anyway.

The AltStore refuses to install the apps with following message:
```
Spotify could not be installed. Spotify requires additional permissions not specified by the source.

These permissions must be declared by the source in order for AltStore to install this app:

Entitlement:
Game Center (com.apple.developer.game-center)
Group Activities (com.apple.developer.group-session)
Health (com.apple.developer.healthkit)
Sensitive Health Data (com.apple.developer.healthkit.access)

Privacy Permission:
Apple Music (NSAppleMusicUsageDescription)
Bluetooth (NSBluetoothAlwaysUsageDescription)
Bluetooth (Peripherals) (NSBluetoothPeripheralUsageDescription)
Face ID (NSFaceIDUsageDescription)
Health (Add) (NSHealthUpdateUsageDescription)
Health (NSHealthShareUsageDescription)
Local Network (NSLocalNetworkUsageDescription)
Photos (Add) (NSPhotoLibraryAddUsageDescription)
Photos (NSPhotoLibraryUsageDescription)
User Tracking (NSUserTrackingUsageDescription)
```

**Comment by yodaluca23** [comment]
Do you have a link to a source that does work?

**Comment by bpresles** [comment]
Yes for example UTM:

https://raw.githubusercontent.com/utmapp/altstore-repo/refs/heads/master/config.json

**Comment by bpresles** [comment]
I opened a PR with fixed AltStore repository file for all the source apps (SpotC++, SpotveeC and SpotilifeC): https://github.com/SpotCompiled/SpotC-Repo/pull/3

**Comment by yodaluca23** [comment]
> I opened a PR with fixed AltStore repository file for all the source apps (SpotC++, SpotveeC and SpotilifeC): https://github.com/SpotCompiled/SpotC-Repo/pull/3

Thank you, 🙏 I have merged it.

**Comment by ZeppLu** [comment]
@yodaluca23 The proposed changes seem to be overwritten by last two commits, thus the apps once again failed to be installed from within AltStore. I'm curious how these JSONs are generated, maybe we should find a way to automate?
https://github.com/SpotCompiled/SpotC-Repo/commit/a622a566f64ff1c299b3250ffcf5b4574b9f5c8f
https://github.com/SpotCompiled/SpotC-Repo/commit/6e60d2984c578b7bfbfb45a4a79a8f085b55ca59

**Comment by yodaluca23** [comment]
> @yodaluca23 The proposed changes seem to be overwritten by last two commits, thus the apps once again failed to be installed from within AltStore. I'm curious how these JSONs are generated, maybe we should find a way to automate?
> https://github.com/SpotCompiled/SpotC-Repo/commit/a622a566f64ff1c299b3250ffcf5b4574b9f5c8f
> https://github.com/SpotCompiled/SpotC-Repo/commit/6e60d2984c578b7bfbfb45a4a79a8f085b55ca59

I did automate it which one is it saying it's missing I'm really confused...

**Comment by ZeppLu** [comment]
> What is it saying it's missing I'm really confused...

For SpotveeC:

> Spotify could not be installed. Spotify requires additional permissions not specified by the source.
> 
> These permissions must be declared by the source in order for AltStore to install this app:
> 
> Entitlement:
> Game Center (com.apple.developer.game-center)

For SpotC++:

> Spotify could not be installed. Spotify requires additional permissions not specified by the source.
> 
> These permissions must be declared by the source in order for AltStore to install this app:
> 
> Entitlement:
> Debuggable (get-task-allow)
> Game Center (com.apple.developer.game-center)

**Comment by yodaluca23** [comment]
> > What is it saying it's missing I'm really confused...
> 
> For SpotveeC:
> 
> > Spotify could not be installed. Spotify requires additional permissions not specified by the source.
> > 
> > These permissions must be declared by the source in order for AltStore to install this app:
> > 
> > Entitlement:
> > Game Center (com.apple.developer.game-center)
> 
> For SpotC++:
> 
> > Spotify could not be installed. Spotify requires additional permissions not specified by the source.
> > 
> > These permissions must be declared by the source in order for AltStore to install this app:
> > 
> > Entitlement:
> > Debuggable (get-task-allow)
> > Game Center (com.apple.developer.game-center)

But their in the source's entitlements array...

https://github.com/SpotCompiled/SpotC-Repo/blob/main/AltStore Repo.json

**Comment by ZeppLu** [comment]
OK, seems today's commits brought the permissions back, good. I can confirm yesterday they are missing.
https://github.com/SpotCompiled/SpotC-Repo/commit/99546036a29b4c9d67c14cab903a93766dbdffb0
https://github.com/SpotCompiled/SpotC-Repo/commit/322476fe841be7cdac59831f1bca641f21fb7202

**Comment by yodaluca23** [comment]
> OK, seems today's commits brought the permissions back, good. I can confirm yesterday they are missing.
> https://github.com/SpotCompiled/SpotC-Repo/commit/99546036a29b4c9d67c14cab903a93766dbdffb0
> https://github.com/SpotCompiled/SpotC-Repo/commit/322476fe841be7cdac59831f1bca641f21fb7202

OK, if that is the case, then I am remembering now I did not do a release in between the time which I updated a section of it that makes it a lot more reliable in getting all the entitlement and privacy keys from now on this should never be an issue again **theoretically** as it's completely automated and hopefully should work.

**Comment by yodaluca23** [comment]
> > OK, seems today's commits brought the permissions back, good. I can confirm yesterday they are missing.
> > https://github.com/SpotCompiled/SpotC-Repo/commit/99546036a29b4c9d67c14cab903a93766dbdffb0
> > https://github.com/SpotCompiled/SpotC-Repo/commit/322476fe841be7cdac59831f1bca641f21fb7202
> 
> OK, if that is the case, then I am remembering now I did not do a release in between the time which I updated a section of it that makes it a lot more reliable in getting all the entitlement and privacy keys from now on this should never be an issue again **theoretically** as it's completely automated and should hopefully *just work.*
