### ISSUE TITLE
Cannot add source to AltStore

### ISSUE THREAD

**Issue by acarrilloortiz** [SpotCompiled/SpotveeC#21]
![IMG_2612](https://github.com/user-attachments/assets/a9adb18b-6263-4cb4-81d0-089d2b68588b)

**Comment by yodaluca23** [comment]
> how did you fixed?

If you're getting the same message, that means you're using AltStore PAL, which means that the apps installed through that have to be notarized by Apple. For one Apple will never notarize a tweaked app two, I'm not paying however much it costs to do so even if it was possible.
