### ISSUE TITLE
Spotify is not available anymore?

### ISSUE THREAD

**Issue by RVMidget** [SpotCompiled/SpotveeC#22]
This app worked for me for about 2 weeks, now when i try to open the app, a pop up showing "spotify is niet meer beschikbaar" comes up. (in the same format of a battery level notification) That is dutch for "spotify is not available anymore. Is this for everyone? Is there a fix or a new version of the app I can use?

**Comment by yodaluca23** [comment]
Nothing to do with the app, however you signed it, got revoked or your blacklisted.
