### ISSUE TITLE
AltStore PAL in Europe 

### ISSUE THREAD

**Issue by mamsles** [SpotCompiled/SpotveeC#4]
Hello,
Thank you for all the work you've done. I wanted to know if it was possible to add the application to the European version of AltStore PAL because when I use this link: "https://tiny.one/SpotC" it doesn't work.
Thanks

**Comment by yodaluca23** [comment]
No, the PAL version uses official sideloading supported by Apple. It requires the application to be "notarized" by Apple, and Apple will never notarize a tweaked app, as its copyright infringement, could be seen as malicious, probably be sued, etc.
