### ISSUE TITLE
Cannot add source

### ISSUE THREAD

**Issue by arthursbg** [SpotCompiled/SpotveeC#5]
"The given Data was not valid JSON." it says with both options.

**Comment by yodaluca23** [comment]
> "The given Data was not valid JSON." it says with both options.

I forgot a comma 😅 fixed now, thank you.

**Comment by arthursbg** [comment]
ty

**Comment by arthursbg** [comment]
wait, now it says:
![IMG_6303](https://github.com/SpotCompiled/SpotveeC/assets/74960323/03bcbd4e-020c-46a5-af92-700d686e3eb4)

**Comment by yodaluca23** [comment]
> wait, now it says:
> 
> ![IMG_6303](https://github.com/SpotCompiled/SpotveeC/assets/74960323/03bcbd4e-020c-46a5-af92-700d686e3eb4)
> 
> 

Fixed, I guess I really rushed the last release 😅

**Comment by arthursbg** [comment]
ty
