### ISSUE TITLE
Spotify Forceful Closure Upon Navigating to "Home" from "EveeSpotify"

### ISSUE THREAD

**Issue by 3xynos7** [SpotCompiled/SpotveeC#6]
When navigating through the app, encountered an issue where the application abruptly closes after performing specific steps. This issue occurs when users follow the steps outlined below:

Steps to Reproduce:
1. Click on the user profile icon.
2. Navigate to "Settings and Privacy."
3. Select "EeveeSpotify."
4. Proceed by clicking on "Home."

**Comment by yodaluca23** [comment]
"It's because Spotify does some stuff with viewcontrollers. Known issue and is not going to be fixed, just use the back button"

https://github.com/whoeevee/EeveeSpotify/issues/86#issuecomment-2106066361
