### ISSUE TITLE
Cannot add source to AltStore

### ISSUE THREAD

**Issue by GitHubUser7926** [SpotCompiled/SpotveeC#7]
This seemed like the best Spotify Premium so i wanted to add its source so i can get new versions without going to the GitHub page but i get this error. Is it an issue on the dev’s end?
![IMG_9159](https://github.com/SpotCompiled/SpotveeC/assets/81097714/666af262-aa90-4bf6-89d5-d8ee523dfa70)

**Comment by yodaluca23** [comment]
Update to the latest beta.

**Comment by GitHubUser7926** [comment]
> Update to the latest beta.

Altstore beta? I thought you have to subscribe to their patreon?

**Comment by yodaluca23** [comment]
> Altstore beta? I thought you have to subscribe to their patreon?

Nah, just use altstore complete source, the .ipas are on the public CDN..

https://bit.ly/altstore-complete-min

**Comment by Ale-su** [comment]
for me it says this, couldn't add the repo so i sideloaded the ipa ![image](https://github.com/SpotCompiled/SpotveeC/assets/76785050/730c4e8e-af3b-4a57-bb7c-cef36867db15)

**Comment by yodaluca23** [comment]
Fixed

**Comment by GitHubUser7926** [comment]
![image](https://github.com/SpotCompiled/SpotveeC/assets/81097714/65294250-87fc-413b-bf8c-97ae4e32512b)

It works now with AltStore Beta thanks. Will close now
