### ISSUE TITLE
when installing from the repo through altstore it installs the oldest version (1.0)

### ISSUE THREAD

**Issue by Ale-su** [SpotCompiled/SpotveeC#8]
like the title says every spotify compiled app on the repo (i mean all 3 of then) havethis problem where the newest shown version is the first release, idk if its a problem with alstore beta 

![image](https://github.com/SpotCompiled/SpotveeC/assets/76785050/346e331d-c5e2-4fd3-b205-2110faaaf484)

![image](https://github.com/SpotCompiled/SpotveeC/assets/76785050/873d81ce-9e0a-474c-8bd0-6afee62f44b9)

**Comment by yodaluca23** [comment]
Thank you, looks like I put the releases in reverse order, I have fixed, should up date in a bit.

**Comment by Ale-su** [comment]
yeah now it works

**Comment by Ale-su** [comment]
![image](https://github.com/SpotCompiled/SpotveeC/assets/76785050/b4d6b7bc-f394-4861-acb7-f60cf88b4e94)
![image](https://github.com/SpotCompiled/SpotveeC/assets/76785050/7559e069-0f64-4677-ba32-a40df0a50cab)

**Comment by yodaluca23** [comment]
1.2.3 and 1.1.3 are the latest for those...

**Comment by Ale-su** [comment]
yeah my bad sorry
