### ISSUE TITLE
Add OpenSpotifySafariExtension plugin

### ISSUE THREAD

**Issue by mamsles** [SpotCompiled/SpotveeC#9]
Hello,
Is it possible to add the "OpenSpotifySafariExtension" plugin from whoeevee to future versions of the application? 
https://github.com/whoeevee/OpenSpotifySafariExtension
Thanks

**Comment by yodaluca23** [comment]
This is only meant to have EeveeSpotify and nothing else, if you want the [OpenSpotifySafariExtension](https://github.com/whoeevee/OpenSpotifySafariExtension), and other QOL enhancements checkout [SpotC++](https://github.com/SpotCompiled/SpotC-Plus-Plus).
